security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CONTRIBUTOR:  ROLE_USER
        ROLE_MANAGER:     [ROLE_USER, ROLE_CONTRIBUTOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONTRIBUTOR, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_CONTRIBUTOR, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer: true
            logout:
                path: /logout
                target: /admin
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, role: ROLE_CONTRIBUTOR }
        - { path: ^/admin/, role: ROLE_CONTRIBUTOR }
        - { path: ^/app_admin.php/admin$, role: ROLE_CONTRIBUTOR }
        - { path: ^/app_admin.php/admin/, role: ROLE_CONTRIBUTOR }
