parameters:
    domainview: 
        localhost: Demo
    viewpath:
        Demo: www.mysite.com
    page404: /404.html

    widgets:
        abListbox:
            label: Accessible and customizable listbox
            css:
                - css/listbox.css
            js: 
                - js/listbox.js
                - js/abListbox.js
        abDatepicker:
            label: Accessible and customizable datepicker
            css: 
                - css/datepicker.css
            js: 
                - js/locales/%locale%.js
                - js/datepicker.js
                - js/abDatepicker.js
        jEditable:
            label: In place form field editor
            css: 
            js: 
                - lib/jquery.auto-grow-input.min.js
                - lib/jquery.inputmask.bundle.min.js
                - js/jquery.jeditable.js
                - js/jquery.jeditable.autogrow.js
                - js/jquery.jeditable.number.js
                - js/jquery.jeditable.date.js
                - js/jquery.jeditable.money.js
                - js/jquery.jeditable.percent.js
                - js/jEditable.js
        AutocompletionListbox:
            label: List box with auto-completion
            css: 
                - lib/jquery.auto-complete.css
            js: 
                - lib/jquery.auto-complete.min.js
                - js/AutocompletionListbox.js
        geoAPILocalities:
            label: Insee code obtained by autocompletion on the name of the commune or its postal code
            deps:
                - AutocompletionListbox
            css: 
            js: 
                - js/geoAPILocalities.js
        geoAPILocalitiesEditable:
            label: Insee code obtained by autocompletion on the name of the commune or its postal code (In place mode)
            deps:
                - AutocompletionListbox
                - jEditable
            css: 
            js: 
                - js/jquery.jeditable.geoAPILocalities.js
                - js/geoAPILocalitiesEditable.js
        geoAPIZipCode:
            label: Postal code obtained by autocompletion on the name of the commune or its postal code
            deps:
                - AutocompletionListbox
            css: 
            js: 
                - js/geoAPIZipCode.js
        geoAPIZipCodeEditable:
            label: Postal code obtained by autocompletion on the name of the commune or its postal code (In place mode)
            deps:
                - AutocompletionListbox
                - jEditable
            css: 
            js: 
                - js/jquery.jeditable.geoAPIZipCode.js
                - js/geoAPIZipCodeEditable.js
        geoAPIMaps:
            label: Insee code obtained from a France map
            deps:
                - geoAPILocalities
            css: 
                - lib/leaflet.css
                - css/geoapimaps.css
            js:
                - https://maps.googleapis.com/maps/api/js?key=<YOUR_API_KEY_HERE> async defer
                - lib/leaflet.js
                - lib/leaflet-color-markers.js
                - lib/leaflet-providers.js
                - lib/Leaflet.GoogleMutant.js
                - js/geoAPIMaps.js

    # api configuration
    # api:
        # <simulator-name>:
            # step: 1
            # action: compute

    # Deployment configuration
    # deployment:
        # localhost: cp -f "{local.rootdir}/{local.file}" "c:/var/www/html/simudev/{remote.dir}/"
        # remotehost: rsync -a {local.rootdir}/{local.file} user@remoteserver:/var/www/html/simudev/{remote.file}
