parameters:

services:
    kernel.listener.g6k_exception_listener:
        class: EUREKA\G6KBundle\EventListener\G6KExceptionListener
        arguments: [ @kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    g6k.file_uploader:
        class: EUREKA\G6KBundle\Services\FileUploader
        arguments: ['%g6k_upload_directory%']
    
    g6k.deployer:
        class: EUREKA\G6KBundle\Services\Deployer
        arguments: [ @kernel, @translator ]
            

    # TwigExtensions
    g6k.twig.filters_extension:
        class: EUREKA\G6KBundle\Twig\Extension\Filters
        tags:
            - { name: twig.extension }

    # Twig string template loader
    g6k.twig_loader.string:
        class: EUREKA\G6KBundle\Twig\Loader\StringTemplateLoader
        tags:
            - { name: twig.loader }
